name: KTPPlugin
main: me.azenet.KTPPlugin.KTPPlugin
version: 2.0

commands:
   ktp:
      description: KTP Control
      usage: /ktp <subcommand>
      permission: ktp.main
      aliases:
          - uh
          - stf

permissions:
    ktp.main:
        description: Permet d'utiliser la commande /ktp
        default: op
# TO BE REMOVED
